language: c
install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y autotools-dev
  - sudo pip install cpp-coveralls
before_script:
  - ./autogen.sh
  - ./configure
script:
  - make check
after_success:
  - coveralls
