install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y autotools-dev lcov
  - sudo pip install cpp-coveralls --use-mirrors
before_script:
  - ./autogen.sh
  - ./configure
script:
  - make check
after_success:
  - coveralls
